// Placeholder Firebase configuration.
//
// This file is normally generated by running:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
// from the root of this Flutter project, against your own Firebase project.
// That command overwrites this file with real API keys/app IDs for each
// platform you target. Until you do that, `Firebase.initializeApp()` will
// fail fast and main.dart shows a "connect Firebase" screen instead of a
// blank crash.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not configured for this platform yet — run `flutterfire configure`.');
    }
  }

  static const web = FirebaseOptions(
    apiKey: 'AIzaSyB-XGWe72H5NZPmTX9ck_y33RRqODyZp94',
    appId: '1:392494713569:web:188ae0ad2050cadbcf45a0',
    messagingSenderId: '392494713569',
    projectId: 'podium-9b4bf',
    authDomain: 'podium-9b4bf.firebaseapp.com',
    storageBucket: 'podium-9b4bf.firebasestorage.app',
    measurementId: 'G-VBQPPJGQWC',
  );

  static const android = FirebaseOptions(
    apiKey: 'AIzaSyAzn7Iis8J6nW3yZaeekSg91nSbs7mUF8s',
    appId: '1:392494713569:android:a78fdeb4e7fa6319cf45a0',
    messagingSenderId: '392494713569',
    projectId: 'podium-9b4bf',
    storageBucket: 'podium-9b4bf.firebasestorage.app',
  );

  static const ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME.appspot.com',
    iosBundleId: 'com.podium.app.podium',
  );
}

bool get isFirebaseConfigured {
  if (kIsWeb) return DefaultFirebaseOptions.web.apiKey != 'REPLACE_ME';
  switch (defaultTargetPlatform) {
    case TargetPlatform.android:
      return DefaultFirebaseOptions.android.apiKey != 'REPLACE_ME';
    case TargetPlatform.iOS:
      return DefaultFirebaseOptions.ios.apiKey != 'REPLACE_ME';
    default:
      return false;
  }
}
