// Fetches the badges' symbols — the game-icons.net icons named by each
// BadgeDef.symbol in lib/logic/badges.dart, as 'author/name' — from the
// icons' repository, and writes their outlines to
// lib/widgets/badge_symbol_data.dart, with their authors' names as the
// licence gives them: the icons are under CC BY 3.0, so the app credits
// them (see badgeSymbolsCredit).
//
// Run it again after giving a badge a new symbol:
//   dart run tool/badge_symbols.dart
import 'dart:convert';
import 'dart:io';

const _out = 'lib/widgets/badge_symbol_data.dart';
const _repo = 'https://raw.githubusercontent.com/game-icons/icons/master';

Future<String> _get(HttpClient client, String url) async {
  final request = await client.getUrl(Uri.parse(url));
  request.headers.set(HttpHeaders.userAgentHeader, 'podium-badge-symbols');
  final response = await request.close();
  final body = await response.transform(utf8.decoder).join();
  if (response.statusCode != 200) throw HttpException('${response.statusCode} on $url');
  return body;
}

/// 'Caro Asercion', 'PriorBlue'… → 'caroasercion', 'priorblue': a name the
/// way its folder spells it, give or take dashes.
String _key(String name) => name.toLowerCase().replaceAll(RegExp('[^a-z0-9]'), '');

Future<void> main() async {
  final symbols = {for (final m in RegExp(r"symbol: '([a-z0-9-]+/[a-z0-9-]+)'").allMatches(File('lib/logic/badges.dart').readAsStringSync())) m.group(1)!}.toList()..sort();
  final client = HttpClient();
  try {
    final paths = <String, String>{};
    for (final symbol in symbols) {
      final svg = await _get(client, '$_repo/$symbol.svg');
      if (svg.contains('transform=') && !RegExp(r'transform="translate\(0,\s*0\)"').hasMatch(svg)) throw StateError('$symbol is transformed: draw it by hand');
      // Every icon sits on a full-size background square, left out.
      final d = [for (final m in RegExp(r' d="([^"]+)"').allMatches(svg)) if (m.group(1) != 'M0 0h512v512H0z') m.group(1)!];
      if (d.isEmpty) throw StateError('no outline in $symbol');
      paths[symbol] = d.join('|');
    }
    // The licence lists each author, by the name of their folder.
    final licence = await _get(client, '$_repo/license.txt');
    final names = {for (final m in RegExp(r'^- ([^,\n]+?)(?:,| -|$)', multiLine: true).allMatches(licence)) _key(m.group(1)!.trim()): m.group(1)!.trim()};
    final authors = {for (final s in symbols) s.split('/').first}.toList()..sort();
    final out = StringBuffer()
      ..writeln('// GENERATED by tool/badge_symbols.dart — run it again rather than editing')
      ..writeln('// this file.')
      ..writeln('//')
      ..writeln('// The badges\' symbols: icons from game-icons.net, by the authors below,')
      ..writeln('// under CC BY 3.0 (https://creativecommons.org/licenses/by/3.0/).')
      ..writeln()
      ..writeln('/// The symbols\' authors, as the icons\' licence names them, by the folder')
      ..writeln('/// that holds their icons.')
      ..writeln('const kBadgeSymbolAuthors = <String, String>{');
    for (final folder in authors) {
      final name = names[_key(folder)];
      if (name == null) throw StateError('$folder is not among the licence\'s authors');
      out.writeln("  '$folder': '$name',");
    }
    out
      ..writeln('};')
      ..writeln()
      ..writeln('/// Each symbol, \'author/name\': its SVG outline in a 512 × 512 box — or')
      ..writeln('/// outlines, split by |.')
      ..writeln('const kBadgeSymbolPaths = <String, String>{');
    for (final symbol in symbols) {
      out.writeln("  '$symbol': '${paths[symbol]}',");
    }
    out.writeln('};');
    File(_out).writeAsStringSync(out.toString());
    stdout.writeln('${symbols.length} symbols by ${authors.length} authors written to $_out.');
  } finally {
    client.close();
  }
}
